<?php
$base = rtrim(dirname($_SERVER['SCRIPT_NAME']), '/');
session_start();

require_once dirname(__DIR__) . '/backend/db.php';
require_once dirname(__DIR__) . '/backend/config.php';
require_once BACKEND_ROOT . '/src/Services/TemplateService.php';

use App\Services\TemplateService;

// ✅ LOAD TEMPLATE SERVICE
$service = new TemplateService();
$templateId = $_GET['id'] ?? null;

if (!$templateId) {
    header("Location: <?= $base ?>/frontend/select_mode.php");
    exit;
}

$template = $service->get($templateId);

if (!$template) {
    die("❌ Template no encontrado");
}
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Generar CFDI</title>
    <link rel="stylesheet" href="<?= $base ?>/frontend/assets/styles.css">
</head>
<body>

<?php include __DIR__ . '/partials/sidebar.php'; ?>

<div class="main">
    <div class="container">
        <div class="card">
            <h2>Generar CFDI</h2>
            <p>Ingresa los datos para generar el CFDI con la addenda.</p>

            <form id="cfdiForm" method="POST" action="<?= $base ?>/backend/public/generate_cfdi_raw.php">
                <input type="hidden" name="template_id" value="<?= htmlspecialchars($templateId) ?>">
                
                <!-- Fields will be dynamically generated by JavaScript -->
                <div id="formFields"></div>
                
                <button type="submit" class="btn blue full">Generar CFDI</button>
            </form>
        </div>

        <div class="card">
            <h3>👁 Vista previa</h3>
            <pre id="preview">Cargando...</pre>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    fetch('<?= $base ?>/backend/public/preview_addenda.php?template_id=<?= urlencode($templateId) ?>')
        .then(r => r.text())
        .then(html => {
            document.getElementById('preview').textContent = html;
        })
        .catch(e => {
            document.getElementById('preview').textContent = 'Error loading preview: ' + e.message;
        });
});
</script>

</body>
</html>